### ISSUE TITLE
Doesn't work on batch 

### ISSUE THREAD

**Issue by atinghosh** [IssamLaradji/elastic_transform#1]
Thanks for the implementation. 
I can't make it work for a batch of images, when I pass a tensor of size (batch_size, channel, H, W) it throws an error if batch_size is >= 2.

**Comment by IssamLaradji** [comment]
Hi @atinghosh I fixed the bug, can you try again?

(I had to remove a rogue `.squeeze()` that caused batch mode to fail)

**Comment by atinghosh** [comment]
Thanks a lot @IssamLaradji, it works now! 

I was wondering if for the batch implementation we could have different alpha and sigma for different images in the batch. So instead of passing a single real value for alpha and sigma, we could pass an array of the same size as the batch_size for both alpha and sigma.

**Comment by IssamLaradji** [comment]
Nice! I think it is doable with `alpha` as it would be an element-wise multiplication between `alpha[i]` and `images[i]`.

But I don't think it is doable with `sigma` as there doesn't seem to be a way to construct gaussian kernels in batch mode :(.

**Comment by atinghosh** [comment]
Thanks a lot. 

Yes, indeed it seems to be straightforward to implement per image alpha in the batch, but not so for sigma. One workaround could be to pass an image with batch_size=1 in a for loop, but for a large batch that would be quite slow. I will close this issue.
